import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import MainDesktopNavigation from "@/components/navbar/DesktopNavbar";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Suspense fallback={<>Loading...</>}>
          <MainDesktopNavigation />
          {children}
          </Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}
