import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, SignInButton } from "@clerk/nextjs";
import MainDesktopNavigation from "@/components/navbar/DesktopNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <MainDesktopNavigation />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
